vouchers:
  voucher_name_1:
    command: "/example command"
    name: "&6Voucher Name 1"  # Color-coded name using Minecraft color codes
    lore:
      - "&eThis voucher allows you to execute a command."
      - "&7Command: &f/example command"
  
  voucher_name_2:
    command: "/another example"
    name: "&5Voucher Name 2"
    lore:
      - "&eThis voucher allows you to execute another command."
      - "&7Command: &f/another example"
