name: VoucherPlugin
main: com.dragonsmith.voucherplugin.VoucherPlugin
version: 1.0
api-version: 1.21
author: DragonSmith
description: A plugin that provides vouchers to execute specific commands.
commands:
  createvoucher:
    description: Create a new voucher.
    usage: /createvoucher <voucher_name> <command>
    permission: voucher.create
  givevoucher:
    description: Give a player a voucher to execute a command.
    usage: /givevoucher <player> <voucher_name>
    permission: voucher.give
permissions:
  voucher.create:
    description: Allows giving vouchers to players.
    default: op
  voucher.give:
    description: Allows giving vouchers to players.
    default: op
  voucher.use:
    description: Allows using vouchers.
    default: true
